import "~/styles/globals.css";
import "@uploadthing/react/styles.css";

import { GeistSans } from "geist/font/sans";
import { ClerkProvider } from "@clerk/nextjs";
import { Header } from "./_components/header";

export const metadata = {
  title: "T3 Gallery Tutorial",
  description: "Generated by a loyal subscriber to Theo on YouTube!",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en" className={`${GeistSans.variable}`}>
        <body className="flex h-screen flex-col gap-4">
          <Header />

          <div className="h-full">{children}</div>
        </body>
      </html>
    </ClerkProvider>
  );
}
